name: Figma to Sketch
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: '*.fig'

jobs:
  fig2sketch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: italia/figma-to-sketch-action@v1.0.0 # https://github.com/italia/figma-to-sketch-action
        with:
          files: 'file-da-sostituire.fig' # File di input .fig (Figma) separati da `|`
          output_files: 'file-da-sostituire.sketch' # File di output .sketch (Sketch) risultanti separati da `|`
      - uses: EndBug/add-and-commit@v9
        with:
          author_name: Bot
          author_email: noreply@designers.italia.it
          message: 🤖 update converted Sketch file
          # Pull before committing, so that HEAD is updated if there
          # have been any commits while the converter was running.
          #
          # `true` would be more elegant once https://github.com/EndBug/add-and-commit/issues/498
          # is fixed
          pull: " "
